### Article Short Info
GET localhost:8081/api/v1/article/get3TypeArticle/

### create article
POST localhost:8081/api/v1/article/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MTExMTcsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzNjk3NTE3LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.CMbES9v8XecwtqCAwzp6UBNFbJaoS4l7sc3C5ho3O5iqSOcgcwb8uGk8thT8QwZb1encUuNbjEbNzAGGR8vcTw
Content-Type: application/json

{
  "title": "bbbb",
  "description": "bbbb",
  "content": "bbbbbbbb",
  "shared_count": 0,
  "attachId": 4,
  "region_id": 1,
  "category_id": 1
}

### update article
POST localhost:8081/api/v1/article/private/1b321832-598a-4997-bbbf-5d1ef0de4fc3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzOTEwMDgsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzNDc3NDA4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Oni3VOKYAqmPuG0nQnzikBeZ-37PkRHQiG3FaDynPEOp1P_pqGu2OliWeqE3iFsaXn032-4iA1TiKKxjUpf9xw
Content-Type: application/json

{
  "title": "aaaaaaa",
  "description": "aaa",
  "content": "aaaaaaaaa",
  "shared_count": 0,
  "image_id": 4,
  "region_id": 1,
  "category_id": 1
}

### delete article
DELETE localhost:8081/api/v1/article/1b321832-598a-4997-bbbf-5d1ef0de4fc3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNzU1NzAsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzNDYxOTcwLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.4D3-SENWbYnA6yijGfgjMZ_W-3ROgZ5psH3ZUXVzFT9Es48pF3AAyr0HPuMl7ah4-_TCby9CyUV-qhLkUCM_Zw

### change status
PUT localhost:8081/api/v1/article/1b321832-598a-4997-bbbf-5d1ef0de4fc3

